language: java
jdk:
- oraclejdk8
script: gradle test
notifications:
  slack:
    secure: hLCHcL3BnT4hXI1LQfPN8gOj9dEa9GFNIb8Fq7WT+dGPq3LoQpRUpbXzIGZ8f/uspsqTF+7ejVtENLVSY9+b89f1vpDRqiKhOrVMQKB1OK8rXZnJNENdgH6Rmddc/GzP/hB+Cpy9Otfq/GPkFCluOdJcHLGwlwkdtIe3kHs60jZIenLRbz81i+QprZWFEqlHeCGq0LKyu5hZZEqdl6JCs6+qNfhyFsEgubP04U/KZS7BQkA6xaU/KElWlWdNynwwppCpkSJIEGN+5uyLBgLaZCyeezdrzl/MLV5e5U1QqK6CKD2FeJiJCzju5jT5+T+OJF5AVRbo0t26VNBEebKTnymawKpVHfLlaJgXroNjm3OtOhxycvKTPfUCgjz7ca+xVm3RO8pBV4jUIhDLAEGS2SEfD+zVp9dyclNWLepmgCBtFNqnaLf8K7fbEV0bzelQZ3+ElIWQQ7RGF/lifZZe1Ube4gIY4SAIltc/gO8HwRUIKQS8TiuYCMIUNsQUawdJeQDOj3PtQvDWPiiopfZmVd2s7oqQM2pIbK4VsFRrQJ1k/1wXIVQLHxX5AjyFY49CKxBB2ho+Qzi82mciRQIKwSJMUKNdeutxYBo+AvcT9VICRcfFj6j2PWySH1csoF0r7KNfpJKzKGYNWvYhaa4Ot5CONJBj2ikoSKHDuiET2MU=
  email: false
deploy:
  provider: heroku
  api_key:
    secure: aCcM1tLiewQsosBb0BuEzmfDynXfSnRW+ipyay/pTcUQYkcRoaxToqQgdQNzmcq1ZCY/ZQzKMLmCG8ZpD9BCjOaOjwYzOVa2EXuwGVQFKiYbhsN6A05SatRG24dXMD1jdpd65A/cB2UDru0MjAmmWC2QH/xK5lw92NBv+6MOW/X6Sw+I6E0ajbsKuU/O+oJ7PxsWph92A2WlikISsuXvEwFdjqO4E/fpqRC6ij3Jj4bNLCWWQ3daJo4hBp53PDr7yjFbbOoGgZTcZ1IQN8zWRfLKvvz7GqRtWmCZeeTd/fzblKgf9P3VgHPfgb3tQVn5K1A9f9vjxwWHp8VGOrWrmS9CNpEaAe2mJ5NRjF70AVKCrAHJ7aFeCKI3lVq/tqxlwmy6OfP3X4S8gDFvSjCPU/Bmbik0OiNyvurbjSg3dSaJ7bfknnEh806nC+/uDKGZCSdQXipr1nr7EkapAaUE40DHO6n+a7WQM4EY8do+XXwnj0Fmk4LSlp1AQeYwokCOjep0/HnX16RbFO9E9mWIQ9q9zzFj6oVG3YUQjYpU5TA9T9WVP0jSmKox27D/Aw8lZ5frelXYBWooTY+fOGys2WGOMIU8u0Mv2FnVJvzBlqV+6F2SOuI1olqZRKV7XUpFDLA559DO2KaxDYXycedrImqvWhbgPE51VBiSGb6YrAg=
  app: breakout-development
  on:
    repo: BreakOutEvent/breakout-backend
    branch: develop
services:
- mysql
before_script:
- mysql -e "create database IF NOT EXISTS test;"