language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
script: sbt test
notifications:
  slack:
    secure: hLCHcL3BnT4hXI1LQfPN8gOj9dEa9GFNIb8Fq7WT+dGPq3LoQpRUpbXzIGZ8f/uspsqTF+7ejVtENLVSY9+b89f1vpDRqiKhOrVMQKB1OK8rXZnJNENdgH6Rmddc/GzP/hB+Cpy9Otfq/GPkFCluOdJcHLGwlwkdtIe3kHs60jZIenLRbz81i+QprZWFEqlHeCGq0LKyu5hZZEqdl6JCs6+qNfhyFsEgubP04U/KZS7BQkA6xaU/KElWlWdNynwwppCpkSJIEGN+5uyLBgLaZCyeezdrzl/MLV5e5U1QqK6CKD2FeJiJCzju5jT5+T+OJF5AVRbo0t26VNBEebKTnymawKpVHfLlaJgXroNjm3OtOhxycvKTPfUCgjz7ca+xVm3RO8pBV4jUIhDLAEGS2SEfD+zVp9dyclNWLepmgCBtFNqnaLf8K7fbEV0bzelQZ3+ElIWQQ7RGF/lifZZe1Ube4gIY4SAIltc/gO8HwRUIKQS8TiuYCMIUNsQUawdJeQDOj3PtQvDWPiiopfZmVd2s7oqQM2pIbK4VsFRrQJ1k/1wXIVQLHxX5AjyFY49CKxBB2ho+Qzi82mciRQIKwSJMUKNdeutxYBo+AvcT9VICRcfFj6j2PWySH1csoF0r7KNfpJKzKGYNWvYhaa4Ot5CONJBj2ikoSKHDuiET2MU=
  email: false