version: '3.1'
services:
  mariadb:
    image: mariadb
    healthcheck:
      test: bash -c "mysqladmin ping -s"
      interval: 2s
      timeout: 2s
      retries: 30
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=breakout
    ports:
      - 3306:3306
