USE `${BREAKOUT}`;

ALTER TABLE `location` ADD COLUMN `speed` DOUBLE DEFAULT NULL;
ALTER TABLE `location` ADD COLUMN `seconds_difference` BIGINT DEFAULT NULL;
ALTER TABLE `location` ADD COLUMN `distance_km` DOUBLE DEFAULT NULL;
