name: Test and build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      SPRING_PROFILES_ACTIVE: test
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Mysql Setup
        run : |
          sudo systemctl start mysql.service
          mysql -e 'DROP DATABASE IF EXISTS ${{ env.DB_DATABASE }}; CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Run Gradle
        run: gradle test
  build_and_push_docker_to_registry:
    name: Push Docker image to Registry
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: breakout
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/breakout-backend:${{ env.BRANCH }}
